// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:texnomart_clone/data/source/locale/hive_data/favourite.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CartAdapter());
    registerAdapter(FavouriteAdapter());
  }
}
